language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
branches:
  only:
    - master
services:
  - docker
before_install:
  - docker-compose --version
  - docker version
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
deploy:
   provider: cloudfoundry
   username: $PIVOTAL_USERNAME
   password: $PIVOTAL_PASSWORD
   api: https://api.run.pivotal.io
   organization: $PIVOTAL_ORG
   space: development
   script: cf push shoppingcart_identity --docker-image henrygustavo/shopping_cart_identity

notifications:
  email:
    on_success: never
    on_failure: always